package com.app.skycast.domain.util

import com.app.skycast.domain.model.city.CountryCode

val countryCodes = listOf(
    CountryCode("Afghanistan", "AF", "AFG", "+93"),
    CountryCode("Albania", "AL", "ALB", "+355"),
    CountryCode("Algeria", "DZ", "DZA", "+213"),
    CountryCode("American Samoa", "AS", "ASM", "+1 684"),
    CountryCode("Andorra", "AD", "AND", "+376"),
    CountryCode("Angola", "AO", "AGO", "+244"),
    CountryCode("Anguilla", "AI", "AIA", "+1 264"),
    CountryCode("Antigua and Barbuda", "AG", "ATG", "+1 268"),
    CountryCode("Argentina", "AR", "ARG", "+54"),
    CountryCode("Armenia", "AM", "ARM", "+374"),
    CountryCode("Australia", "AU", "AUS", "+61"),
    CountryCode("Austria", "AT", "AUT", "+43"),
    CountryCode("Azerbaijan", "AZ", "AZE", "+994"),
    CountryCode("Bahamas", "BS", "BHS", "+1 242"),
    CountryCode("Bahrain", "BH", "BHR", "+973"),
    CountryCode("Bangladesh", "BD", "BGD", "+880"),
    CountryCode("Barbados", "BB", "BRB", "+1 246"),
    CountryCode("Belarus", "BY", "BLR", "+375"),
    CountryCode("Belgium", "BE", "BEL", "+32"),
    CountryCode("Belize", "BZ", "BLZ", "+501"),
    CountryCode("Benin", "BJ", "BEN", "+229"),
    CountryCode("Bhutan", "BT", "BTN", "+975"),
    CountryCode("Bolivia", "BO", "BOL", "+591"),
    CountryCode("Bosnia and Herzegovina", "BA", "BIH", "+387"),
    CountryCode("Botswana", "BW", "BWA", "+267"),
    CountryCode("Brazil", "BR", "BRA", "+55"),
    CountryCode("Brunei", "BN", "BRN", "+673"),
    CountryCode("Bulgaria", "BG", "BGR", "+359"),
    CountryCode("Burkina Faso", "BF", "BFA", "+226"),
    CountryCode("Burundi", "BI", "BDI", "+257"),
    CountryCode("Cambodia", "KH", "KHM", "+855"),
    CountryCode("Cameroon", "CM", "CMR", "+237"),
    CountryCode("Canada", "CA", "CAN", "+1"),
    CountryCode("Cape Verde", "CV", "CPV", "+238"),
    CountryCode("Cayman Islands", "KY", "CYM", "+1 345"),
    CountryCode("Chad", "TD", "TCD", "+235"),
    CountryCode("Chile", "CL", "CHL", "+56"),
    CountryCode("China", "CN", "CHN", "+86"),
    CountryCode("Colombia", "CO", "COL", "+57"),
    CountryCode("Comoros", "KM", "COM", "+269"),
    CountryCode("Congo", "CG", "COG", "+242"),
    CountryCode("Croatia", "HR", "HRV", "+385"),
    CountryCode("Cuba", "CU", "CUB", "+53"),
    CountryCode("Cyprus", "CY", "CYP", "+357"),
    CountryCode("Czech Republic", "CZ", "CZE", "+420"),
    CountryCode("Denmark", "DK", "DNK", "+45"),
    CountryCode("Djibouti", "DJ", "DJI", "+253"),
    CountryCode("Dominica", "DM", "DMA", "+1 767"),
    CountryCode("Dominican Republic", "DO", "DOM", "+1 809"),
    CountryCode("Ecuador", "EC", "ECU", "+593"),
    CountryCode("Egypt", "EG", "EGY", "+20"),
    CountryCode("El Salvador", "SV", "SLV", "+503"),
    CountryCode("Estonia", "EE", "EST", "+372"),
    CountryCode("Ethiopia", "ET", "ETH", "+251"),
    CountryCode("Fiji", "FJ", "FJI", "+679"),
    CountryCode("Finland", "FI", "FIN", "+358"),
    CountryCode("France", "FR", "FRA", "+33"),
    CountryCode("Gabon", "GA", "GAB", "+241"),
    CountryCode("Gambia", "GM", "GMB", "+220"),
    CountryCode("Georgia", "GE", "GEO", "+995"),
    CountryCode("Germany", "DE", "DEU", "+49"),
    CountryCode("Ghana", "GH", "GHA", "+233"),
    CountryCode("Greece", "GR", "GRC", "+30"),
    CountryCode("Grenada", "GD", "GRD", "+1 473"),
    CountryCode("Guatemala", "GT", "GTM", "+502"),
    CountryCode("Guinea", "GN", "GIN", "+224"),
    CountryCode("Guyana", "GY", "GUY", "+592"),
    CountryCode("Haiti", "HT", "HTI", "+509"),
    CountryCode("Honduras", "HN", "HND", "+504"),
    CountryCode("Hungary", "HU", "HUN", "+36"),
    CountryCode("Iceland", "IS", "ISL", "+354"),
    CountryCode("India", "IN", "IND", "+91"),
    CountryCode("Indonesia", "ID", "IDN", "+62"),
    CountryCode("Iran", "IR", "IRN", "+98"),
    CountryCode("Iraq", "IQ", "IRQ", "+964"),
    CountryCode("Ireland", "IE", "IRL", "+353"),
    CountryCode("Israel", "IL", "ISR", "+972"),
    CountryCode("Italy", "IT", "ITA", "+39"),
    CountryCode("Jamaica", "JM", "JAM", "+1 876"),
    CountryCode("Japan", "JP", "JPN", "+81"),
    CountryCode("Jordan", "JO", "JOR", "+962"),
    CountryCode("Kazakhstan", "KZ", "KAZ", "+7"),
    CountryCode("Kenya", "KE", "KEN", "+254"),
    CountryCode("Kuwait", "KW", "KWT", "+965"),
    CountryCode("Kyrgyzstan", "KG", "KGZ", "+996"),
    CountryCode("Laos", "LA", "LAO", "+856"),
    CountryCode("Latvia", "LV", "LVA", "+371"),
    CountryCode("Lebanon", "LB", "LBN", "+961"),
    CountryCode("Lesotho", "LS", "LSO", "+266"),
    CountryCode("Liberia", "LR", "LBR", "+231"),
    CountryCode("Libya", "LY", "LBY", "+218"),
    CountryCode("Liechtenstein", "LI", "LIE", "+423"),
    CountryCode("Lithuania", "LT", "LTU", "+370"),
    CountryCode("Luxembourg", "LU", "LUX", "+352"),
    CountryCode("Madagascar", "MG", "MDG", "+261"),
    CountryCode("Malawi", "MW", "MWI", "+265"),
    CountryCode("Malaysia", "MY", "MYS", "+60"),
    CountryCode("Maldives", "MV", "MDV", "+960"),
    CountryCode("Mali", "ML", "MLI", "+223"),
    CountryCode("Malta", "MT", "MLT", "+356"),
    CountryCode("Mexico", "MX", "MEX", "+52"),
    CountryCode("Moldova", "MD", "MDA", "+373"),
    CountryCode("Monaco", "MC", "MCO", "+377"),
    CountryCode("Mongolia", "MN", "MNG", "+976"),
    CountryCode("Montenegro", "ME", "MNE", "+382"),
    CountryCode("Morocco", "MA", "MAR", "+212"),
    CountryCode("Mozambique", "MZ", "MOZ", "+258"),
    CountryCode("Myanmar", "MM", "MMR", "+95"),
    CountryCode("Namibia", "NA", "NAM", "+264"),
    CountryCode("Nepal", "NP", "NPL", "+977"),
    CountryCode("Netherlands", "NL", "NLD", "+31"),
    CountryCode("New Zealand", "NZ", "NZL", "+64"),
    CountryCode("Nicaragua", "NI", "NIC", "+505"),
    CountryCode("Niger", "NE", "NER", "+227"),
    CountryCode("Nigeria", "NG", "NGA", "+234"),
    CountryCode("North Korea", "KP", "PRK", "+850"),
    CountryCode("Norway", "NO", "NOR", "+47"),
    CountryCode("Oman", "OM", "OMN", "+968"),
    CountryCode("Pakistan", "PK", "PAK", "+92"),
    CountryCode("Palestine", "PS", "PSE", "+970"),
    CountryCode("Panama", "PA", "PAN", "+507"),
    CountryCode("Papua New Guinea", "PG", "PNG", "+675"),
    CountryCode("Paraguay", "PY", "PRY", "+595"),
    CountryCode("Peru", "PE", "PER", "+51"),
    CountryCode("Philippines", "PH", "PHL", "+63"),
    CountryCode("Poland", "PL", "POL", "+48"),
    CountryCode("Portugal", "PT", "PRT", "+351"),
    CountryCode("Qatar", "QA", "QAT", "+974"),
    CountryCode("Romania", "RO", "ROU", "+40"),
    CountryCode("Russia", "RU", "RUS", "+7"),
    CountryCode("Rwanda", "RW", "RWA", "+250"),
    CountryCode("Saudi Arabia", "SA", "SAU", "+966"),
    CountryCode("Senegal", "SN", "SEN", "+221"),
    CountryCode("Serbia", "RS", "SRB", "+381"),
    CountryCode("Seychelles", "SC", "SYC", "+248"),
    CountryCode("Sierra Leone", "SL", "SLE", "+232"),
    CountryCode("Singapore", "SG", "SGP", "+65"),
    CountryCode("Slovakia", "SK", "SVK", "+421"),
    CountryCode("Slovenia", "SI", "SVN", "+386"),
    CountryCode("South Africa", "ZA", "ZAF", "+27"),
    CountryCode("South Korea", "KR", "KOR", "+82"),
    CountryCode("Spain", "ES", "ESP", "+34"),
    CountryCode("Sri Lanka", "LK", "LKA", "+94"),
    CountryCode("Sudan", "SD", "SDN", "+249"),
    CountryCode("Suriname", "SR", "SUR", "+597"),
    CountryCode("Sweden", "SE", "SWE", "+46"),
    CountryCode("Switzerland", "CH", "CHE", "+41"),
    CountryCode("Syria", "SY", "SYR", "+963"),
    CountryCode("Taiwan", "TW", "TWN", "+886"),
    CountryCode("Tanzania", "TZ", "TZA", "+255"),
    CountryCode("Thailand", "TH", "THA", "+66"),
    CountryCode("Togo", "TG", "TGO", "+228"),
    CountryCode("Trinidad and Tobago", "TT", "TTO", "+1 868"),
    CountryCode("Tunisia", "TN", "TUN", "+216"),
    CountryCode("Turkey", "TR", "TUR", "+90"),
    CountryCode("Uganda", "UG", "UGA", "+256"),
    CountryCode("Ukraine", "UA", "UKR", "+380"),
    CountryCode("United Arab Emirates", "AE", "ARE", "+971"),
    CountryCode("United Kingdom", "GB", "GBR", "+44"),
    CountryCode("United States", "US", "USA", "+1"),
    CountryCode("Uruguay", "UY", "URY", "+598"),
    CountryCode("Uzbekistan", "UZ", "UZB", "+998"),
    CountryCode("Vanuatu", "VU", "VUT", "+678"),
    CountryCode("Vatican City", "VA", "VAT", "+39"),
    CountryCode("Venezuela", "VE", "VEN", "+58"),
    CountryCode("Vietnam", "VN", "VNM", "+84"),
    CountryCode("Yemen", "YE", "YEM", "+967"),
    CountryCode("Zambia", "ZM", "ZMB", "+260"),
    CountryCode("Zimbabwe", "ZW", "ZWE", "+263")
)